exclude: ^docs/notebooks/
repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      args: ["--config=pyproject.toml", "--check", "--diff"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.4"
    hooks:
    - id: flake8
      args: ["--config=.flake8"]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
    - id: isort